include theos/makefiles/common.mk

APPLICATION_NAME = Skunk
Skunk_FILES = main.m SkunkApplication.mm RootViewController.mm
Skunk_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
