#! /bin/sh
if [ `whoami` = root ]; then
  echo "Use to copy sendrsa to a Mac!" 
  echo "Enter the ip or local address of your Mac (Ex. Carly-D@carly-d-mac.local)"

  read $ADDRESS
  scp /usr/bin/sendrsa "$ADDRESS"
  echo "Success!";

else echo "please run as root"

fi