#!/bin/sh
A=$(date +%Y-%m-%d)
B=$(date +%A) 
cd ~/Documents/git
git pull origin master
wget --no-check-certificate -qO- https://wol.jw.org/en/wol/h/r1/lp-e | sed -n "/$B/,/<\/a><\/p>/p" | sed 's/a href="\/e/a href="https:\/\/wol.jw.org\/e/g' > ~/Documents/git/DailyText/txt
git add *
git commit -m "$A: Daily Text"
git push origin master

