#!/usr/bin/python

import requests
import re
import datetime
import yagmail
import unicodedata


subs = []
with open('/var/mobile/Documents/git/DailyText/subs') as file:
    n = 0
    for line in file:
        line = line.strip() #preprocess line
        subs.insert(n, line)
        n+1


#variable declares
now = datetime.datetime.now()
day = now.strftime("%d").lstrip('0')
month = now.strftime("%m").lstrip('0')

url = 'https://wol.jw.org/en/wol/dt/r1/lp-e/' + now.strftime('%Y') + '/' + month + '/' + day

#TEXT IS EXTRACTED BETWEEN THESE FIELDS
start = '<div class="itemData">\n'
end = '</p>\r\n</div>\r\n</div>\r\n</div>\r\n'

#fetch html
raw = requests.get(url).text
dt = raw[raw.find(start)+len(start):raw.rfind(end)].replace('/en/wol/bc/', 'https://wol.jw.org/en/wol/bc/').replace('\n','')

dailytext = '<!DOCTYPE html><html dir="ltr" lang="en"><head></head><center><body>' + unicodedata.normalize('NFKD', dt).encode('ascii','ignore').replace('.<wbr /></em><a href="https://wol.jw', '. - <wbr /></em><a href="https://wol.jw') + '\n\n<em></em></body></center></html>'



#email dailytext

dtmail = yagmail.SMTP("dcarltondunlap@gmail.com", "Gogators95")



dtmail.send(to = 'dcarltondunlap@hotmail.com', subject = 'Daily Text', contents = [dailytext])